<?php

namespace Ecommerce\EcommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function findArray($array)
    {
        $qb=$this->createQueryBuilder('p')
                 ->select('p')
                 ->where('p.id IN (:array)')
                 ->setParameter('array',$array);
        return $qb->getQuery()->getResult();
    }
    
}
